name: Update Homebrew Formula

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:      

jobs:
  update_formula:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write

    steps:

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Set up git
        uses: Homebrew/actions/git-user-config@master

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install dependencies
        run: |
          brew install jq 

      - name: Run update script
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        run: |
          #!/bin/bash

          set -euo pipefail

          echo "Check of new tar versions...."
          json_output=$(brew livecheck --tap alvaro-aguirre-cl/homebrew-esopipes --json)

          echo "$json_output" | jq -c '.[] | select(.version.outdated == true)' | while read -r formula; do

              formula_name=$(echo "$formula" | jq -r '.formula')
              current_version_number=$(echo "$formula" | jq -r '.version.current')
              new_version_number=$(echo "$formula" | jq -r '.version.latest')
              echo "Checking for new version of $formula_name..."
              
              formula_path="Formula/$formula_name.rb" # Cambia este valor al path de tu fórmula
              formula="alvaro-aguirre-cl/homebrew-esopipes/$formula_name"

              current_url=$(grep -E '^[[:space:]]*url ".*"' -m 1 "$formula_path" | awk -F'"' '{print $2}')
              echo "Current tarball URL: $current_url"

              tarball_url=${current_url//"$current_version_number"/"$new_version_number"}
              echo "New tarball URL: $tarball_url"

              echo "Downloading new tarball from $tarball_url..."
              curl -L "$tarball_url" -o /tmp/source-"$new_version_number".tar.gz

              if [ ! -f /tmp/source-"$new_version_number".tar.gz ]; then
                  echo "Error: Failed to download tarball."
                  exit 1
              fi

              new_sha256=$(shasum -a 256 /tmp/source-"$new_version_number".tar.gz | awk '{print $1}')
              echo "New version number: $new_version_number"
              echo "New checksum: $new_sha256"
              echo "Tarbal URL: $tarball_url"

              echo "Updating the formula with brew bump-formula-pr..."
              brew bump-formula-pr \
              --sha256="$new_sha256" \
              --url="$tarball_url" \
              --force \
              --no-browse \
              "$formula"

              if brew bump-formula-pr \
                  --sha256="$new_sha256" \
                  --url="$tarball_url" \
                  --force \
                  --no-browse \
                  "$formula"; then
                  echo "Formula updated successfully!"
              else
                  echo "Error updating formula with brew bump-formula-pr"
                  exit 1
              fi
          done

          echo "Process completed..."
        shell: bash